version: '3'

services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: qwe123
    ports:
      # container port和主機port的配對
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    # volumes: ./data:/var/lib/mysql 將當前目錄下的 data 資料夾掛載到容器中的 /var/lib/mysql 目錄。

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: qwe123

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  redis-admin:
    depends_on:
      - redis #讓redis先啟動，再啟動redis-admin
    image: rediscommander/redis-commander:latest
    container_name: redis-admin
    hostname: redis-admin
    restart: always
    ports:
      - 8081:80
    environment:
      REDIS_HOST: redis #連結redis
